from pathlib import Path
import tempfile
from auto_loop_strings_v51 import run_auto_loop_v51
XML='<?xml version="1.0"?>\n<score-partwise version="4.0">\n<part-list><score-part id="P1"><part-name>Violin 1</part-name></score-part><score-part id="P2"><part-name>Violin 2</part-name></score-part><score-part id="P3"><part-name>Viola</part-name></score-part><score-part id="P4"><part-name>Cello</part-name></score-part></part-list>\n<part id="P1"><measure number="1"><attributes><divisions>4</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes><direction><sound tempo="90"/></direction>\n<note><pitch><step>G</step><octave>3</octave></pitch><duration>4</duration><notations><slur type="start"/></notations></note>\n<note><pitch><step>E</step><octave>6</octave></pitch><duration>4</duration><notations><slur type="continue"/><glissando type="start"/></notations></note>\n<note><pitch><step>A</step><octave>3</octave></pitch><duration>4</duration><notations><slur type="continue"/></notations></note>\n<note><pitch><step>D</step><octave>6</octave></pitch><duration>4</duration><notations><slur type="stop"/></notations></note></measure>\n<measure number="2"><note><rest/><duration>8</duration></note><note><pitch><step>A</step><octave>4</octave></pitch><duration>4</duration><notations><slur type="start"/></notations></note><note><pitch><step>B</step><octave>4</octave></pitch><duration>4</duration><notations><slur type="stop"/></notations></note></measure></part>\n<part id="P2"><measure number="1"><attributes><divisions>4</divisions></attributes><note><rest/><duration>16</duration></note></measure><measure number="2"><note><rest/><duration>16</duration></note></measure></part>\n<part id="P3"><measure number="1"><attributes><divisions>4</divisions></attributes><note><rest/><duration>16</duration></note></measure><measure number="2"><note><rest/><duration>16</duration></note></measure></part>\n<part id="P4"><measure number="1"><attributes><divisions>4</divisions></attributes><note><rest/><duration>16</duration></note></measure><measure number="2"><note><rest/><duration>16</duration></note></measure></part>\n</score-partwise>'
with tempfile.TemporaryDirectory() as td:
    td=Path(td);score=td/"fallback.musicxml";score.write_text(XML)
    report,rp=run_auto_loop_v51(score,td/"out",td/"policy.json",port=49582,mock=True,max_round=1,
                                sample_rate=8000,coverage_limit=.55,local_context=.4,max_local_context_seconds=12)
    assert report["rounds"][0]["mode"]=="full_fallback",report["rounds"][0]
    assert report["rounds"][0]["fallback_reason"].startswith("local_"),report["rounds"][0]["fallback_reason"]
    assert report["final"]["mode"]=="full_fallback_after_local",report["final"]
    assert Path(report["final"]["midi"]).exists() and Path(report["final"]["wav"]).exists()
print("SONICRAFT v5.1 low-confidence local -> full A/B/C/D fallback smoke OK",report["rounds"][0]["fallback_reason"],report["final"]["status"])
