#!/usr/bin/env python3
from __future__ import annotations
"""Generate deterministic multi-note clean-room bowed-string phrase supervision.

All score/control material and rendered audio are generated by SONICRAFT's
independently authored physical teacher. No third-party model, audio, preset,
checkpoint, or hidden metadata is consumed.
"""
import argparse
from collections import Counter
from dataclasses import asdict, replace
import hashlib, json, sys
from pathlib import Path
from typing import Any

import mido
import numpy as np
import soundfile as sf

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from cleanroom_bowed_synth import ARTICULATIONS, RANGES, random_controls, synthesize_section
from sound_forge import analyze_audio, sha256_file

DATASET_ID = 'synthetic_cleanroom_bowed_v18'
PHRASE_SCHEMA = 1
PHRASE_VERSION = 'cleanroom_phrase_corpus_v1'
FPS = 100
INSTRUMENT_NAMES = ('violin_1','violin_2','viola','cello')
PHRASE_FAMILIES = ('legato_scale','portamento_pair','spiccato_pattern','tremolo_sustain','expressive_arc','mixed_bowing')
ART = {name:i for i,name in enumerate(ARTICULATIONS)}


def _hash(value: Any) -> str:
    raw=json.dumps(value,ensure_ascii=False,sort_keys=True,separators=(',',':'))
    return hashlib.sha256(raw.encode('utf-8')).hexdigest()


def _split(sample_id: str) -> str:
    n=int(hashlib.sha256(sample_id.encode()).hexdigest()[:8],16)%1000
    return 'train' if n<900 else ('val' if n<950 else 'test')


def _pitch(inst: int, p: float) -> float:
    lo,hi=RANGES[int(inst)]; return float(np.clip(p,lo,hi))


def _event(start,duration,pitch,art,velocity,dynamics,legato=0.,slide_from=None,vibrato_depth=0.,bow_change=.25):
    return {
        'start_sec':float(start),'duration_sec':float(duration),'pitch':float(pitch),
        'articulation':int(ART[art]),'articulation_name':art,
        'velocity':float(np.clip(velocity,.05,1.)),'dynamics':float(np.clip(dynamics,.05,1.)),
        'legato':float(np.clip(legato,0.,1.)),'slide_from':None if slide_from is None else float(slide_from),
        'vibrato_depth_cents':float(max(0.,vibrato_depth)),'bow_change_prob':float(np.clip(bow_change,0.,1.)),
    }


def make_phrase(rng, instrument: int, family: str, seconds: float, bpm: float):
    lo,hi=RANGES[int(instrument)]; a=min(hi-8,lo+7); b=max(a+1,hi-7)
    root=float(rng.integers(a,b+1)); direction=-1 if rng.random()<.5 else 1; vel=float(rng.uniform(.48,.92)); ev=[]
    if family=='legato_scale':
        steps=[0,2,4,5] if rng.random()<.5 else [0,-2,-4,-5]
        for j,step in enumerate(steps):
            st=[0,.235,.47,.705][j]*seconds
            ev.append(_event(st,min(.30*seconds,seconds-st),_pitch(instrument,root+step),'legato',vel+.04*j,.52+.10*j,1.,None,18+8*j,.12))
    elif family=='portamento_pair':
        p0=_pitch(instrument,root); p1=_pitch(instrument,p0+direction*int(rng.choice([3,5,7,9]))); st=.47*seconds
        ev.append(_event(0,.54*seconds,p0,'expressive_long',vel,.60,.9,None,24,.08))
        ev.append(_event(st,seconds-st,p1,'portamento',min(1.,vel+.05),.68,1.,p0,30,.08))
    elif family=='spiccato_pattern':
        pattern=[0,4,2,5,4,2,0,-2]; slot=seconds/len(pattern)
        for j,step in enumerate(pattern):
            ev.append(_event(j*slot,slot*.72,_pitch(instrument,root+step),'spiccato',np.clip(vel+rng.uniform(-.1,.1),.3,1.),np.clip(.66+rng.uniform(-.08,.08),.25,1.),0.,None,0.,.95))
    elif family=='tremolo_sustain':
        p0=_pitch(instrument,root); p1=_pitch(instrument,root+direction*int(rng.choice([2,3,5]))); st=.5*seconds
        ev=[_event(0,.54*seconds,p0,'tremolo',vel,.58,.4,None,8,.98),_event(st,seconds-st,p1,'tremolo',min(1.,vel+.07),.72,.55,None,10,.98)]
    elif family=='expressive_arc':
        offs=[0,direction*3,direction*5]; starts=[0,.31*seconds,.64*seconds]; durs=[.38*seconds,.40*seconds,.36*seconds]
        for j in range(3):
            ev.append(_event(starts[j],min(durs[j],seconds-starts[j]),_pitch(instrument,root+offs[j]),'expressive_long',np.clip(vel+(.08 if j==1 else -.03),.25,1.),[.44,.82,.53][j],.9,None,[18,42,30][j],.1))
    elif family=='mixed_bowing':
        names=['marcato','legato','spiccato','portamento','sustain']; offs=[0,2*direction,5*direction,3*direction,7*direction]
        starts=np.asarray([0,.20,.41,.57,.78])*seconds; durs=np.asarray([.23,.27,.15,.28,.22])*seconds; prev=None
        for j,name in enumerate(names):
            p=_pitch(instrument,root+offs[j]); ev.append(_event(float(starts[j]),min(float(durs[j]),seconds-float(starts[j])),p,name,np.clip(vel+rng.uniform(-.08,.08),.3,1.),[.78,.60,.72,.66,.55][j],1. if name in {'legato','portamento'} else 0.,prev if name=='portamento' else None,26 if name in {'legato','portamento','sustain'} else 0.,.9 if name in {'marcato','spiccato'} else .2)); prev=p
    else: raise ValueError(f'unknown phrase family: {family}')
    return ev


def build_curves(events, seconds: float, bpm: float):
    frames=max(2,int(round(seconds*FPS))); t=np.arange(frames,dtype=np.float32)/FPS
    z=lambda v=0.:np.full(frames,float(v),np.float32)
    c={
        'pitch':z(),'gate':z(),'onset':z(),'velocity':z(),'dynamics':z(),'vibrato':z(),'expression':z(),'legato':z(),'pitchbend':z(),
        'transition_speed':z(.5),'short_tightness':z(.45),'attack_character':z(.38),'note_progress':z(),
        'phrase_position':np.clip(t/max(seconds,1e-6),0,1).astype(np.float32),'prev_interval':z(.5),'next_interval':z(.5),
        'bow_change_prob':z(.25),'vibrato_onset':z(),'tempo_bpm':z(bpm),'seconds_per_beat':z(60./bpm),'note_duration_beats':z(),
        'transition_target_ms':z(80),'speed_profile':z(),'vibrato_depth_cents':z(),'vibrato_rate_hz':z(5.2),'vibrato_onset_ms':z(),
        'vibrato_jitter':z(.03),'dynamics_known':z(1),'vibrato_known':z(1),'vibrato_physics_known':z(1),'expression_known':z(1),
        'legato_known':z(1),'pitchbend_known':z(),'timing_known':z(1),'articulation_known':z(1),'articulation_curve':z(),
    }
    for j,e in enumerate(events):
        a=max(0,int(round(e['start_sec']*FPS))); b=min(frames,max(a+1,int(round((e['start_sec']+e['duration_sec'])*FPS))))
        if a>=frames: continue
        p=float(e['pitch']); art=int(e['articulation']); c['gate'][a:b]=1;c['pitch'][a:b]=p;c['velocity'][a:b]=e['velocity'];c['dynamics'][a:b]=e['dynamics'];c['expression'][a:b]=e['dynamics'];c['legato'][a:b]=e['legato'];c['articulation_curve'][a:b]=art;c['bow_change_prob'][a:b]=e['bow_change_prob'];c['vibrato_depth_cents'][a:b]=e['vibrato_depth_cents'];c['vibrato'][a:b]=min(1.,e['vibrato_depth_cents']/60.);c['note_duration_beats'][a:b]=e['duration_sec']/(60./bpm);c['note_progress'][a:b]=np.linspace(0,1,b-a,dtype=np.float32);c['onset'][a:min(frames,a+2)]=1
        c['short_tightness'][a:b]=.86 if art in (ART['staccato'],ART['spiccato']) else .45;c['attack_character'][a:b]=.75 if art in (ART['marcato'],ART['spiccato']) else .38;c['transition_speed'][a:b]=.28 if art==ART['portamento'] else (.72 if art==ART['spiccato'] else .52);c['transition_target_ms'][a:b]=150 if art==ART['portamento'] else (45 if art==ART['spiccato'] else 80);c['speed_profile'][a:b]=-.4 if art==ART['portamento'] else (.45 if art==ART['spiccato'] else 0);c['vibrato_rate_hz'][a:b]=5.+.9*e['dynamics']
        vo=min(320.,max(40.,e['duration_sec']*1000*.22));c['vibrato_onset_ms'][a:b]=vo;c['vibrato_onset'][a:b]=min(1.,vo/1000.);c['pitchbend_known'][a:b]=1. if art==ART['portamento'] else 0.
        pp=float(events[j-1]['pitch']) if j else p; np_=float(events[j+1]['pitch']) if j+1<len(events) else p;c['prev_interval'][a:b]=np.clip((p-pp+12)/24,0,1);c['next_interval'][a:b]=np.clip((np_-p+12)/24,0,1)
        if e.get('slide_from') is not None and b-a>=2:
            tr=max(2,min(b-a,int(round((b-a)*.48)))); actual=np.full(b-a,p,np.float32);actual[:tr]=np.linspace(float(e['slide_from']),p,tr,dtype=np.float32);c['pitchbend'][a:b]=(actual-p)/12.
    active=np.flatnonzero(c['gate']>.5)
    if active.size:
        first,last=int(active[0]),int(active[-1]);c['pitch'][:first]=c['pitch'][first];c['pitch'][last+1:]=c['pitch'][last]
        for i in range(first+1,last+1):
            if c['gate'][i]<.5 and c['pitch'][i]==0:c['pitch'][i]=c['pitch'][i-1]
    return c


def render_phrase(rng,events,instrument,seconds,sample_rate,seed,section_players):
    n=max(32,int(round(seconds*sample_rate))); mix=np.zeros(n,np.float64)
    for j,e in enumerate(events):
        st=int(round(e['start_sec']*sample_rate));
        if st>=n: continue
        art=int(e['articulation']); dur=min(e['duration_sec']+.055,seconds-e['start_sec']); ctrl=random_controls(rng,instrument,art); slide=e['pitch']-e['slide_from'] if e.get('slide_from') is not None else 0.
        ctrl=replace(ctrl,pitch=e['pitch'],velocity=e['velocity'],bow_speed=float(np.clip(.24+.72*e['dynamics'],.08,.98)),bow_force=float(np.clip(.18+.68*e['dynamics'],.08,.96)),vibrato_depth_cents=e['vibrato_depth_cents'],slide_semitones=slide,slide_time=.48 if art==ART['portamento'] else ctrl.slide_time,bow_lift=1. if art in (ART['staccato'],ART['spiccato'],ART['marcato']) else 0.,section_players=max(1,int(section_players)),section_pitch_spread_cents=4.5 if section_players>1 else 0.,section_timing_spread_ms=6. if section_players>1 else 0.,section_bow_spread=.08 if section_players>1 else 0.)
        y=synthesize_section(ctrl,max(.05,dur),sample_rate,seed+1009*j).astype(np.float64); end=min(n,st+len(y));mix[st:end]+=y[:end-st]
    peak=float(np.max(np.abs(mix)))+1e-9
    if peak>.98:mix*=.98/peak
    return mix.astype(np.float32)


def write_midi(events,path:Path,bpm:float):
    mid=mido.MidiFile(type=1,ticks_per_beat=480);track=mido.MidiTrack();mid.tracks.append(track);tempo=mido.bpm2tempo(bpm);track.append(mido.MetaMessage('set_tempo',tempo=tempo,time=0));timeline=[]
    for e in events:
        st=max(0,int(round(mido.second2tick(e['start_sec'],480,tempo))));et=max(st+1,int(round(mido.second2tick(e['start_sec']+e['duration_sec'],480,tempo))));note=int(round(e['pitch']));vel=int(np.clip(20+100*e['velocity'],1,127));timeline += [(st,1,mido.Message('control_change',control=11,value=vel,time=0)),(st,2,mido.Message('note_on',note=note,velocity=vel,time=0)),(et,0,mido.Message('note_off',note=note,velocity=0,time=0))]
    timeline.sort(key=lambda x:(x[0],x[1]));last=0
    for tick,_,msg in timeline:msg.time=max(0,tick-last);track.append(msg);last=tick
    path.parent.mkdir(parents=True,exist_ok=True);mid.save(path)


def _fingerprint(path:Path):
    x,_=sf.read(path,dtype='float32',always_2d=True);mono=np.asarray(x,np.float32).mean(1)
    if mono.size<32:return hashlib.sha256(mono.tobytes()).hexdigest()
    mono/=float(np.max(np.abs(mono)))+1e-9;edges=np.linspace(0,mono.size,49).astype(int);r=np.asarray([np.sqrt(np.mean(mono[edges[i]:max(edges[i]+1,edges[i+1])]**2)+1e-12) for i in range(48)],np.float32);r/=float(r.max())+1e-9;return hashlib.sha256(np.rint(r*31).astype(np.uint8).tobytes()).hexdigest()


def build_phrase_corpus(out_dir:Path,count:int,seconds:float,sample_rate:int,seed:int,section_prob:float):
    audio=out_dir/'audio';curves_dir=out_dir/'control_curves';events_dir=out_dir/'events';midi_dir=out_dir/'midi'
    for p in (audio,curves_dir,events_dir,midi_dir):p.mkdir(parents=True,exist_ok=True)
    rows=[];rejected=[];exact_seen=set();coarse_seen=set();coverage=Counter();rng=np.random.default_rng(seed)
    for i in range(int(count)):
        family=PHRASE_FAMILIES[i%len(PHRASE_FAMILIES)];inst=(i//len(PHRASE_FAMILIES))%4;bpm=float(rng.uniform(58,92));events=make_phrase(rng,inst,family,seconds,bpm);identity={'version':PHRASE_VERSION,'seed':seed,'index':i,'instrument':inst,'family':family,'bpm':round(bpm,6),'events':events};sid=_hash(identity)[:24]
        wavp=audio/f'{sid}.wav';cp=curves_dir/f'{sid}.npz';ep=events_dir/f'{sid}.json';mp=midi_dir/f'{sid}.mid';players=int(rng.choice([2,3,4])) if rng.random()<section_prob else 1
        np.savez_compressed(cp,**build_curves(events,seconds,bpm));ep.write_text(json.dumps(identity,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8');write_midi(events,mp,bpm);sf.write(wavp,render_phrase(rng,events,inst,seconds,sample_rate,seed+i*7919,players),sample_rate,subtype='FLOAT')
        q=analyze_audio(wavp);exact=sha256_file(wavp);coarse=_fingerprint(wavp);dupe='exact' if exact in exact_seen else ('coarse_intra_run' if coarse in coarse_seen else None);ok=bool(not q.hard_reject and q.score>=.45 and dupe is None);primary=Counter(int(x['articulation']) for x in events).most_common(1)[0][0];first=events[0]
        row={'schema_version':PHRASE_SCHEMA,'phrase_version':PHRASE_VERSION,'audio':str(wavp.resolve()),'control_curves':str(cp.resolve()),'events_json':str(ep.resolve()),'midi':str(mp.resolve()),'dataset':DATASET_ID,'dataset_id':DATASET_ID,'training_origin':'modeled','source_kind':'modeled','cleanroom_spec_version':'SONICRAFT-BOWED-1.0','release_blocked':False,'commercial_safe':True,'final_timbre_anchor':False,'independently_authored_controls':True,'proprietary_model_bytes_embedded':False,'sample_id':sid,'split':_split(sid),'phrase_family':family,'instrument':inst,'instrument_name':INSTRUMENT_NAMES[inst],'articulation':primary,'articulation_name':ARTICULATIONS[primary],'pitch':first['pitch'],'velocity':first['velocity'],'dynamics':first['dynamics'],'expression':first['dynamics'],'vibrato':min(1.,first['vibrato_depth_cents']/60.),'legato':first['legato'],'pitchbend':0.,'transition_speed':.5,'short_tightness':.45,'attack_character':.38,'phrase_position':0.,'prev_interval':.5,'next_interval':.5,'bow_change_prob':first['bow_change_prob'],'tempo_bpm':bpm,'note_duration_beats':first['duration_sec']/(60./bpm),'dynamics_known':1.,'vibrato_known':1.,'vibrato_physics_known':1.,'expression_known':1.,'legato_known':1.,'pitchbend_known':1. if family=='portamento_pair' else 0.,'timing_known':1.,'articulation_known':1.,'player':i%8,'section_players':players,'ensemble_kind':'section' if players>1 else 'solo','event_count':len(events),'audio_sha256':exact,'control_curves_sha256':sha256_file(cp),'events_sha256':sha256_file(ep),'midi_sha256':sha256_file(mp),'audio_coarse_fingerprint':coarse,'forge_quality_score':float(q.score),'forge_quality_tier':q.tier,'forge_audio':asdict(q),'forge_reasons':list(q.reasons),'forge_release_eligible':ok}
        if ok:exact_seen.add(exact);coarse_seen.add(coarse);rows.append(row);coverage[(inst,family)]+=1
        else:row['status']='duplicate' if dupe else 'quality_rejected';row['duplicate_kind']=dupe;rejected.append(row);wavp.unlink(missing_ok=True) if dupe else None
    (out_dir/'index.jsonl').write_text('\n'.join(json.dumps(r,ensure_ascii=False) for r in rows)+('\n' if rows else ''),encoding='utf-8');(out_dir/'rejected.jsonl').write_text('\n'.join(json.dumps(r,ensure_ascii=False) for r in rejected)+('\n' if rejected else ''),encoding='utf-8')
    report={'schema_version':PHRASE_SCHEMA,'phrase_version':PHRASE_VERSION,'dataset':DATASET_ID,'requested':count,'accepted':len(rows),'rejected':len(rejected),'seconds':seconds,'sample_rate':sample_rate,'seed':seed,'families':list(PHRASE_FAMILIES),'coverage':{f'{INSTRUMENT_NAMES[i]}:{f}':int(coverage[(i,f)]) for i in range(4) for f in PHRASE_FAMILIES},'control_curve_fps':FPS,'notes':'Modeled phrase supervision only; final_timbre_anchor=false and existing origin-aware sampler policy still applies.'};(out_dir/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8');return report


def main():
    ap=argparse.ArgumentParser(description='Generate SONICRAFT-owned multi-note clean-room bowed-string phrases.');ap.add_argument('--out',default='datasets/generated/cleanroom_phrases_v1');ap.add_argument('--count',type=int,default=2400);ap.add_argument('--seconds',type=float,default=2.0);ap.add_argument('--sample-rate',type=int,default=48000);ap.add_argument('--seed',type=int,default=20260917);ap.add_argument('--section-prob',type=float,default=.20);a=ap.parse_args()
    if a.count<1:raise SystemExit('--count must be >= 1')
    if a.seconds<.35:raise SystemExit('--seconds must be >= 0.35')
    if not 0<=a.section_prob<=1:raise SystemExit('--section-prob must be in [0,1]')
    print(json.dumps(build_phrase_corpus(Path(a.out),a.count,a.seconds,a.sample_rate,a.seed,a.section_prob),ensure_ascii=False,indent=2,sort_keys=True))


if __name__=='__main__':main()
