#include "realtime_shell_core.h"
#include <chrono>
#include <iostream>
#include <string>
#include <vector>
using namespace Sonicraft::ProductShell;
int main(int argc,char**argv){std::string host="127.0.0.1",out="sonicraft_realtime_sim.wav";int port=49337,quantumMs=180,blocks=5;for(int i=1;i<argc;++i){std::string a=argv[i];auto n=[&](){if(i+1>=argc)std::exit(2);return std::string(argv[++i]);};if(a=="--host")host=n();else if(a=="--port")port=std::stoi(n());else if(a=="--out")out=n();else if(a=="--quantum-ms")quantumMs=std::stoi(n());else if(a=="--blocks")blocks=std::stoi(n());}
const uint32_t sr=48000;const int64_t q=int64_t(sr)*std::clamp(quantumMs,80,600)/1000;RendererClient c(host,port);if(!c.ping(sr)){std::cerr<<"service offline\n";return 3;}Timeline tl;Policy p;p.mode=1;p.multiOut=true;p.lookahead=.08f;MixerState mix;mix.master=.70f;mix.feed[4]=.35f;mix.feed[8]=.20f;tl.pushNote(true,0,69,104,0,p.tempo);tl.pushNote(true,1,64,96,0,p.tempo);tl.pushNote(true,2,57,90,0,p.tempo);tl.pushNote(true,3,45,100,0,p.tempo);std::vector<float> all;uint64_t req=240001;std::vector<double> ms;for(int b=0;b<std::max(1,blocks);++b){int64_t start=int64_t(b)*q,end=start+q;if(b==blocks-1){tl.pushNote(false,0,69,0,end-2,p.tempo);tl.pushNote(false,1,64,0,end-2,p.tempo);tl.pushNote(false,2,57,0,end-2,p.tempo);tl.pushNote(false,3,45,0,end-2,p.tempo);}auto ev=tl.contextFor(start,end,int64_t(sr)*4);RenderAudio a;auto t0=std::chrono::steady_clock::now();if(!c.render(ev,start,end,sr,p,req++,a)){std::cerr<<"render failed block="<<b<<"\n";return 4;}auto t1=std::chrono::steady_clock::now();ms.push_back(std::chrono::duration<double,std::milli>(t1-t0).count());auto st=mixToStereo(a,mix);all.insert(all.end(),st.begin(),st.end());if(a.channels!=34){std::cerr<<"expected 34ch multiout\n";return 5;}}
if(!writePcm16Wav(out,all,sr))return 6;double worst=0,sum=0;for(double v:ms){worst=std::max(worst,v);sum+=v;}std::cout<<"v2.4 REALTIME SIM PASS blocks="<<ms.size()<<" quantum_ms="<<quantumMs<<" avg_request_ms="<<(sum/ms.size())<<" max_request_ms="<<worst<<" out="<<out<<"\n";return 0;}
