param([string]$ProjectRoot=(Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)))
$ErrorActionPreference='Stop';$root=(Resolve-Path $ProjectRoot).Path;$stage=Join-Path $root 'release\prebuilt';$app=Join-Path $stage 'App'
if(Test-Path $app){Remove-Item -Recurse -Force $app}
New-Item -ItemType Directory -Force -Path (Join-Path $app 'Manager'),(Join-Path $app 'Runtime'),(Join-Path $app 'Cubase'),(Join-Path $app 'Licenses'),(Join-Path $app 'Tools'),(Join-Path $app 'Standalone'),(Join-Path $app 'Frontend')|Out-Null
Copy-Item -Force (Join-Path $root 'SONICRAFT_AI_Strings_Manager.exe') (Join-Path $app 'Manager')
Copy-Item -Force (Join-Path $root 'manager_release.ps1') (Join-Path $app 'Manager\manager.ps1')
$psh=Join-Path $root 'release\ProductShell';if(Test-Path $psh){Copy-Item -Force (Join-Path $psh '*.exe') (Join-Path $app 'Standalone')}
foreach($n in @('renderer_service.py','audio_take_judge_v37.py','judge_memory_v38.py','score_expression_graph_v40.py','compile_musicxml_strings_v41.py','compile_musicxml_strings_v42.py','string_physical_graph_v42.py','string_physical_runtime_v42.py','string_constraint_solver_v43.py','compile_musicxml_strings_v43.py','string_ensemble_solver_v44.py','string_ensemble_runtime_v44.py','compile_musicxml_strings_v44.py','string_gesture_graph_v45.py','string_gesture_runtime_v45.py','compile_musicxml_strings_v45.py','string_transition_graph_v46.py','string_transition_runtime_v46.py','compile_musicxml_strings_v46.py','string_phrase_longline_v47.py','string_phrase_runtime_v47.py','compile_musicxml_strings_v47.py','string_performance_critic_v48.py','compile_musicxml_strings_v48.py','string_repair_policy_v49.py','audio_io_v49.py','midi_judge_adapter_v49.py','compile_musicxml_strings_v49.py','iterate_strings_v49.py','shadow_render_auto_v50.py','compile_musicxml_strings_v50.py','auto_loop_strings_v50.py','selective_phrase_search_v51.py','shadow_render_selective_v51.py','selective_midi_merge_v51.py','compile_musicxml_strings_v51.py','auto_loop_strings_v51.py','global_performance_coherence_v52.py','compile_musicxml_strings_v52.py','auto_loop_strings_v52.py','conductor_intent_v53.py','compile_musicxml_strings_v53.py','auto_loop_strings_v53.py','conductor_candidate_steering_v54.py','compile_musicxml_strings_v54.py','auto_loop_strings_v54.py','candidate_utility_predictor_v55.py','compile_musicxml_strings_v55.py','auto_loop_strings_v55.py','counterfactual_auditor_v56.py','compile_musicxml_strings_v56.py','auto_loop_strings_v56.py','context_similarity_transfer_v57.py','compile_musicxml_strings_v57.py','auto_loop_strings_v57.py','performance_archetype_memory_v58.py','compile_musicxml_strings_v58.py','auto_loop_strings_v58.py','archetype_mixture_v59.py','compile_musicxml_strings_v59.py','auto_loop_strings_v59.py','evidence_store_v60.py','compile_musicxml_strings_v60.py','auto_loop_strings_v60.py','performance_checkpoint_v61.py','compile_musicxml_strings_v61.py','auto_loop_strings_v61.py','acoustic_runtime_provenance_v62.py','performance_checkpoint_v62.py','compile_musicxml_strings_v62.py','auto_loop_strings_v62.py','compile_midi_performance_v29.py','model_backend.py','release_integrity.py','flow_sampler.py','quartet_interaction.py','frontier_context.py','tile_cache.py','instrument_x_cleanroom.py','polyphony.py','stage_renderer.py','stage_renderer_np.py','control_builder_np.py','ort_model_backend.py','runtime_backend_selector_v24.py','musicxml_import.py','protocol.py','status_client.py','smoke_client.py','renderer_service_launcher.ps1')){Copy-Item -Force (Join-Path $root ('runtime\'+$n)) (Join-Path $app 'Runtime')}
if(Test-Path (Join-Path $root 'SONICRAFT_AI_Renderer_Service.exe')){Copy-Item -Force (Join-Path $root 'SONICRAFT_AI_Renderer_Service.exe') (Join-Path $app 'Runtime')}

$modelCode=Join-Path $app 'Runtime\models';New-Item -ItemType Directory -Force -Path $modelCode|Out-Null
foreach($n in @('__init__.py','adaptive_flow_dit.py','ballad_flow_renderer.py','vibrato_expert.py','performance_experts.py','string_vae64.py')){Copy-Item -Force (Join-Path $root ('runtime\models\'+$n)) $modelCode}
Copy-Item -Force (Join-Path $root 'cubase\*') (Join-Path $app 'Cubase')
Copy-Item -Force (Join-Path $root 'licenses\*') (Join-Path $app 'Licenses')
Copy-Item -Force (Join-Path $root 'frontend\index.html') (Join-Path $app 'Frontend\index.html')
Copy-Item -Force (Join-Path $root 'frontend\editor_server.py') (Join-Path $app 'Frontend\editor_server.py')
Copy-Item -Force (Join-Path $root 'frontend\README_FRONTEND_V64.md') (Join-Path $app 'Frontend\README_FRONTEND_V64.md')
Copy-Item -Force (Join-Path $root 'installer\OPEN_INSTRUMENT_EDITOR_RELEASE.bat') (Join-Path $app 'Tools\OPEN_INSTRUMENT_EDITOR.bat')
Copy-Item -Force (Join-Path $root 'installer\INSTALL_AI_RUNTIME_RELEASE.ps1') (Join-Path $app 'Tools\INSTALL_AI_RUNTIME.ps1')
Copy-Item -Force (Join-Path $root 'installer\STOP_RENDERER_SERVICE.ps1') (Join-Path $app 'Tools\STOP_RENDERER_SERVICE.ps1')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v41.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v41.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v42.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v42.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v43.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v43.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v44.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v44.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v45.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v45.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v46.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v46.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v47.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v47.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v48.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v48.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v49.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v49.bat')
Copy-Item -Force (Join-Path $root 'ITERATE_STRINGS_v49.bat') (Join-Path $app 'Tools\ITERATE_STRINGS_v49.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v50.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v50.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v50.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v50.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v51.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v51.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v51.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v51.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v52.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v52.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v52.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v52.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v53.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v53.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v53.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v53.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v54.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v54.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v54.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v54.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v55.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v55.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v55.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v55.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v56.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v56.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v56.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v56.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v57.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v57.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v57.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v57.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v58.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v58.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v58.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v58.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v59.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v59.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v59.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v59.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v60.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v60.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v60.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v60.bat')
Copy-Item -Force (Join-Path $root 'EVIDENCE_STORE_V60.bat') (Join-Path $app 'Tools\EVIDENCE_STORE_V60.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v61.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v61.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v61.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v61.bat')
Copy-Item -Force (Join-Path $root 'PERFORMANCE_CHECKPOINT_V61.bat') (Join-Path $app 'Tools\PERFORMANCE_CHECKPOINT_V61.bat')
Copy-Item -Force (Join-Path $root 'COMPILE_MUSICXML_STRINGS_v62.bat') (Join-Path $app 'Tools\COMPILE_MUSICXML_STRINGS_v62.bat')
Copy-Item -Force (Join-Path $root 'AUTO_LOOP_STRINGS_v62.bat') (Join-Path $app 'Tools\AUTO_LOOP_STRINGS_v62.bat')
Copy-Item -Force (Join-Path $root 'PERFORMANCE_CHECKPOINT_V62.bat') (Join-Path $app 'Tools\PERFORMANCE_CHECKPOINT_V62.bat')
@{version='7.0.0-rc2';channel='commercial-rc';prebuilt=$true;built_at=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json|Set-Content -Encoding UTF8 (Join-Path $app 'build-info.json')
Write-Host "PREBUILT APP STAGED: $app" -ForegroundColor Green
